/* Generated by scripts/write_docs_ref.py — do not edit. */
window.TAXTRIAGE_DOCS = {
  "ref": "main",
  "version": "main",
  "label": "development",
  "commit": "9739eedce8f800acf58253bbc72f3c606e156429"
};
