/* Generated by scripts/write_docs_ref.py — do not edit. */
window.TAXTRIAGE_DOCS = {
  "ref": "main",
  "version": "main",
  "label": "development",
  "commit": "018430e1923686bdc033010d4a17649c72e2b622"
};
