/* Generated by scripts/write_docs_ref.py — do not edit. */
window.TAXTRIAGE_DOCS = {
  "ref": "main",
  "version": "main",
  "label": "development",
  "commit": "2d30a88c9743b948fc90b0f22e5a46b8ce431554"
};
