/* Generated by scripts/write_docs_ref.py — do not edit. */
window.TAXTRIAGE_DOCS = {
  "ref": "v3.3.10",
  "version": "latest",
  "label": "stable (v3.3.10)",
  "commit": "366c7d7e3a905e199465da57d57735e0e30acd7b"
};
