/* Generated by scripts/write_docs_ref.py — do not edit. */
window.TAXTRIAGE_DOCS = {
  "ref": "v3.3.11",
  "version": "3.3.11",
  "label": "3.3.11",
  "commit": "03b843527f241ba8c112baa96e9e26f8af64f9e7"
};
