#!/usr/bin/env python3
"""
Point the Demo Report tab at `latest` in a versioned (release) documentation build.

The demo is a ~4.5 MB self-contained dist rebuilt from assets/heatmap.html.
Copying it into every version would add megabytes per release to the gh-pages
branch, and it illustrates the report UI rather than documenting release-specific
behaviour, so only `latest` carries the real thing.

In a versioned build it is replaced by a small page that redirects to its
`latest` equivalent — the tab stays in the nav and the URL keeps working:

    /taxtriage/3.3.9/demo-report/  ->  /taxtriage/latest/demo-report/

The Pathogen Sheet is deliberately NOT handled here. It is published in every
version and pinned by scripts/write_docs_ref.py to that version's git ref, so
the 3.3.9 docs show the sheet that shipped in v3.3.9 while `latest` shows main.
It costs nothing to ship, since the CSV is fetched at page load rather than
bundled.

The redirect is relative (`../../<latest>/<slug>/`) so it survives a move to a
custom domain. Two levels up because mike serves each build under a version
directory that `mkdocs build` itself does not create.

Usage:
    python scripts/docs_release_stub.py                 # rewrite the pages
    python scripts/docs_release_stub.py --check         # verify only
    python scripts/docs_release_stub.py --latest v2     # non-default alias name
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# (page file under docs/, human title, one-line explanation)
LIVE_TABS = [
    (
        "demo-report.md",
        "Demo Report",
        "The interactive report demo is rebuilt from the current pipeline, so it "
        "is published with the latest documentation rather than copied into every "
        "release.",
    ),
]

TEMPLATE = """---
title: {title}
hide:
  - toc
  - navigation
---

<!-- Generated by scripts/docs_release_stub.py for versioned builds.
     Raw HTML on purpose: a Markdown link to another mike version would fail
     `mkdocs build --strict`, since the target is not part of this build. -->
<meta http-equiv="refresh" content="0; url=../../{latest}/{slug}/">
<link rel="canonical" href="../../{latest}/{slug}/">

# {title}

{explanation}

<p><a href="../../{latest}/{slug}/"><strong>Continue to {title} &rarr;</strong></a></p>

<p>If you are not redirected automatically, use the link above.</p>
"""


def main() -> int:
    here = Path(__file__).resolve().parent.parent
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="verify without modifying anything")
    ap.add_argument("--latest", default="latest", help="name of the version that hosts the live tabs")
    ap.add_argument("--docs", type=Path, default=here / "docs")
    ap.add_argument("--config", type=Path, default=here / "mkdocs.yml")
    args = ap.parse_args()

    config_text = args.config.read_text(encoding="utf-8") if args.config.is_file() else ""
    problems: list[str] = []

    for page, title, _ in LIVE_TABS:
        if not (args.docs / page).is_file():
            problems.append(f"page not found: docs/{page}")
        # The tab must still be in the nav, otherwise the stub is unreachable
        # and the redirect silently does nothing.
        if f": {page}" not in config_text:
            problems.append(
                f"docs/{page} is not referenced in {args.config.name} nav; "
                "the redirect stub would be unreachable"
            )

    if problems:
        for p in problems:
            print(f"error: {p}", file=sys.stderr)
        return 1

    if args.check:
        print(f"ok: {len(LIVE_TABS)} live-data tabs present and in nav")
        return 0

    for page, title, explanation in LIVE_TABS:
        slug = page[:-3]  # strip .md; MkDocs serves directory URLs
        (args.docs / page).write_text(
            TEMPLATE.format(title=title, slug=slug, latest=args.latest, explanation=explanation),
            encoding="utf-8",
        )
        print(f"  docs/{page} -> redirects to ../../{args.latest}/{slug}/")

    print(f"stubbed {len(LIVE_TABS)} live-data tabs to '{args.latest}'")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
