#!/usr/bin/env python3
"""
Regenerate ``assets/heatmap_boot.js`` — the demo bootstrap payload that makes
``assets/heatmap.html`` openable straight from disk — from pipeline JSON output.

How it works
------------
``bin/make_report.py`` is the single source of truth for the BOOT payload: it
loads ``all.odr.json`` (or per-sample ``*.paths.json``), merges metadata /
annotations / novelty / pathogen sheets, and embeds the result in the report as

    <script>
    window.HEATMAP_BOOT = {...};
    </script>

Rather than duplicating that logic (and drifting from it), this script runs
make_report.py into a throwaway HTML in a temp dir, pulls the payload back out
with ``scripts/extract_heatmap_boot.py``, and writes

    window.HEATMAP_BOOT = {...};

to ``assets/heatmap_boot.js``. Anything make_report.py learns to put in the
payload shows up here for free.

An existing report HTML can also be given directly, in which case no rebuild
happens and the payload is simply lifted out of it.

Usage
-----
    # the usual case: rebuild the demo payload from a run's combined JSON
    python scripts/make_heatmap_boot.py test_output/report/all.odr.json

    # several inputs, plus the extras a real report build would get
    python scripts/make_heatmap_boot.py out/*/all.odr.json \
        --metadata metadata.csv --pathogens assets/pathogen_sheet.csv

    # reuse a report that is already built
    python scripts/make_heatmap_boot.py test_output/report/all.odr.html

    # write somewhere else / keep it compact / preview only
    python scripts/make_heatmap_boot.py all.odr.json -o /tmp/boot.js --minify
    python scripts/make_heatmap_boot.py all.odr.json --info

Any flag this script does not define is forwarded verbatim to make_report.py,
so ``--mintass 5 -mc Primary Potential -p annots.xlsx`` all work unchanged.
Use ``--`` to separate them explicitly if a value would otherwise look like a
flag of this script.
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from extract_heatmap_boot import describe, extract  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
MAKE_REPORT = REPO_ROOT / "bin" / "make_report.py"
TEMPLATE = REPO_ROOT / "assets" / "heatmap.html"
DEFAULT_OUT = REPO_ROOT / "assets" / "heatmap_boot.js"

HEADER = (
    "// Generated by scripts/make_heatmap_boot.py — do not edit by hand.\n"
    "// Source: {src}\n"
    "// Demo bootstrap for assets/heatmap.html; regenerate with:\n"
    "//   python scripts/make_heatmap_boot.py <all.odr.json>\n"
)


def build_report(inputs: list[str], passthrough: list[str], workdir: Path) -> Path:
    """Run make_report.py on ``inputs`` and return the HTML it wrote."""
    if not MAKE_REPORT.exists():
        sys.exit(f"ERROR: not found: {MAKE_REPORT}")

    out_html = workdir / "boot_build.html"
    # Inputs are resolved to absolute paths, and make_report is run from the
    # caller's cwd (it is cwd-independent), so relative paths in BOTH the
    # inputs and any forwarded flags (--metadata, -p, --pathogens, ...) mean
    # what the caller typed rather than something under the repo root.
    cmd = [
        sys.executable, str(MAKE_REPORT),
        "-i", *[str(Path(f).resolve()) for f in inputs],
        "-o", str(out_html),
    ]
    # Let the caller override the template; otherwise use the repo's shell.
    if not any(a in ("-t", "--template") for a in passthrough):
        cmd += ["-t", str(TEMPLATE)]
    cmd += passthrough

    print("[make_heatmap_boot] $ " + " ".join(cmd))
    res = subprocess.run(cmd)
    if res.returncode != 0:
        sys.exit(f"ERROR: make_report.py exited {res.returncode}")
    if not out_html.exists():
        sys.exit(f"ERROR: make_report.py produced no output at {out_html}")
    return out_html


def main() -> None:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "input", nargs="+", metavar="FILE",
        help="One or more all.odr.json / *.paths.json inputs, OR a single "
             "already-built report .html to lift the payload out of.",
    )
    ap.add_argument(
        "-o", "--output", type=Path, default=DEFAULT_OUT,
        help=f"Output JS path (default: {DEFAULT_OUT.relative_to(REPO_ROOT)}).",
    )
    ap.add_argument(
        "--minify", action="store_true",
        help="Write the payload compact, exactly as make_report.py serialized it "
             "(smaller file, unreadable diffs).",
    )
    ap.add_argument("--indent", type=int, default=2,
                    help="Indent for the default pretty output (default: 2).")
    ap.add_argument("--no-header", action="store_true",
                    help="Omit the generated-by comment header.")
    ap.add_argument("--backup", action="store_true",
                    help="Keep the previous file as <output>.bak.")
    ap.add_argument("--info", action="store_true",
                    help="Summarize the payload and write nothing.")
    ap.add_argument("--allow-empty", action="store_true",
                    help="Write the file even when the payload has zero organism "
                         "records (default: refuse — an empty payload is almost "
                         "always a bad input path or an over-strict filter).")
    ap.add_argument("--keep-html", type=Path, default=None, metavar="PATH",
                    help="Also keep the intermediate report HTML at this path.")
    args, passthrough = ap.parse_known_args()
    # argparse leaves a bare "--" separator in the remainder; drop it.
    passthrough = [a for a in passthrough if a != "--"]

    for f in args.input:
        if not Path(f).exists():
            hint = ""
            alt = REPO_ROOT / f
            if not Path(f).is_absolute() and alt.exists():
                hint = f"\n       (did you mean {alt}?)"
            sys.exit(f"ERROR: not found: {Path(f).resolve()}{hint}")

    html_inputs = [f for f in args.input if f.lower().endswith((".html", ".htm"))]
    if html_inputs:
        if len(args.input) > 1:
            sys.exit("ERROR: pass exactly one .html, or only JSON inputs — not a mix.")
        if passthrough:
            print("[make_heatmap_boot] WARNING: ignoring make_report flags "
                  f"({' '.join(passthrough)}) — the payload is read from the HTML as-is.",
                  file=sys.stderr)
        source = Path(html_inputs[0])
        payload, kind = extract(source)
        tmpdir = None
    else:
        tmpdir = Path(tempfile.mkdtemp(prefix="heatmap_boot_"))
        try:
            built = build_report(args.input, passthrough, tmpdir)
            payload, kind = extract(built)
            if args.keep_html:
                args.keep_html.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(built, args.keep_html)
                print(f"[make_heatmap_boot] kept report HTML: {args.keep_html}")
        finally:
            if tmpdir and tmpdir.exists():
                shutil.rmtree(tmpdir, ignore_errors=True)
        source = Path(args.input[0]) if len(args.input) == 1 else Path("multiple inputs")

    n_rec = len(payload.get("records") or [])
    n_samp = len(payload.get("sample_meta") or {})
    print(f"[make_heatmap_boot] payload: {len(payload)} keys, {n_rec:,} records, "
          f"{n_samp} sample(s)  (source: {kind})")

    if not n_rec and not args.allow_empty:
        sys.exit(
            "ERROR: the payload has 0 organism records — refusing to write an empty "
            "heatmap_boot.js.\n"
            "       Check make_report's output above: a 'cannot find ... skipping' line "
            "means the input path was wrong,\n"
            "       and 0 rows from a file that WAS read usually means --mintass / -mc "
            "filtered everything out.\n"
            "       Pass --allow-empty if an empty payload is really what you want."
        )

    if args.info:
        print(describe(payload))
        return

    if args.minify:
        body = json.dumps(payload, ensure_ascii=False, allow_nan=False,
                          separators=(",", ":"))
    else:
        body = json.dumps(payload, ensure_ascii=False, allow_nan=False,
                          indent=args.indent)

    src_label = ", ".join(args.input) if len(args.input) <= 3 else \
        f"{args.input[0]} (+{len(args.input) - 1} more)"
    header = "" if args.no_header else HEADER.format(src=src_label)
    text = f"{header}window.HEATMAP_BOOT = {body};\n"

    out = args.output
    out.parent.mkdir(parents=True, exist_ok=True)
    if args.backup and out.exists():
        bak = out.with_suffix(out.suffix + ".bak")
        shutil.copy2(out, bak)
        print(f"[make_heatmap_boot] backup: {bak}")
    out.write_text(text, encoding="utf-8")
    print(f"✓ {out}  ({len(text):,} chars)")
    print("[make_heatmap_boot] uncomment the heatmap_boot.js <script> in "
          "assets/heatmap.html to load it when opening the shell directly.")


if __name__ == "__main__":
    main()
