#!/usr/bin/env python3
"""
Write docs/javascripts/docs_ref.js, which pins the git ref the documentation
site reads runtime data from.

The Pathogen Sheet tab fetches assets/pathogen_sheet.csv from GitHub when the
page loads rather than bundling it. For versioned docs that ref must match the
release being documented, otherwise the 3.1 docs would show organisms that only
exist on main.

Usage:
    python scripts/write_docs_ref.py                 # defaults to "main"
    python scripts/write_docs_ref.py --ref v3.3.8
    python scripts/write_docs_ref.py --ref v3.3.8 --version 3.3

The file is generated on every build and is gitignored.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from pathlib import Path

# Refuse anything that isn't a plausible branch name or tag, since this value
# is interpolated into a URL the browser fetches.
SAFE_REF = re.compile(r"^[A-Za-z0-9._/-]+$")


def current_ref() -> str:
    """Best-effort git ref for local development."""
    for cmd in (["git", "describe", "--tags", "--exact-match"], ["git", "rev-parse", "--abbrev-ref", "HEAD"]):
        try:
            out = subprocess.run(cmd, capture_output=True, text=True, check=True).stdout.strip()
            if out and out != "HEAD":
                return out
        except (subprocess.CalledProcessError, FileNotFoundError):
            continue
    return "main"


def main() -> int:
    here = Path(__file__).resolve().parent.parent
    ap = argparse.ArgumentParser()
    ap.add_argument("--ref", default=None, help="git ref to read data files from (default: current branch/tag)")
    ap.add_argument("--version", default=None, help="human-readable docs version, e.g. 3.3 or bleeding-edge")
    ap.add_argument("--out", type=Path, default=here / "docs" / "javascripts" / "docs_ref.js")
    args = ap.parse_args()

    ref = args.ref or current_ref()
    if not SAFE_REF.match(ref):
        raise SystemExit(f"error: refusing unsafe ref {ref!r}")

    version = args.version or ref

    body = (
        "/* Generated by scripts/write_docs_ref.py — do not edit. */\n"
        "window.TAXTRIAGE_DOCS = "
        + json.dumps({"ref": ref, "version": version}, indent=2)
        + ";\n"
    )
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(body, encoding="utf-8")
    print(f"docs ref = {ref}  (version {version})  -> {args.out.relative_to(here)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
