/* Generated by scripts/write_docs_ref.py — do not edit. */
window.TAXTRIAGE_DOCS = {
  "ref": "v3.3.10",
  "version": "stable",
  "label": "stable (3.3.10)",
  "commit": "31fe7e78f20cbeaecf62412baf73e75dde38ead6"
};
