/* Generated by scripts/write_docs_ref.py — do not edit. */
window.TAXTRIAGE_DOCS = {
  "ref": "v3.3.11",
  "version": "stable",
  "label": "stable (3.3.11)",
  "commit": "6af1bafcb7d4e416f1b77eff4d48c7e830d08a0b"
};
